version: '2'

services:
  meteor-gomoku:
    image: nphung/meteor-gomoku
    ports:
      - "3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/gomoku
      - ROOT_URL=https://gomoku.elarvee.xyz
    networks:
      - web
    labels:
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:gomoku.elarvee.xyz"
    restart: unless-stopped

  mongodb:
    image: mongo:3
    ports:
      - "27017"
    volumes:
      - ./data:/data/db

networks:
  web:
    external:
      name: traefik_webgateway
